#!/bin/bash
function do_config() {
    read -p "Enter the name of the Dropbox directory you wish to sync [homedir] : " DROPBOX_DIR
    DROPBOX_DIR=${DROPBOX_DIR:-homedir}
    echo
    echo "Downloading Dropbox management script"
    cd $HOME
    mkdir -p $HOME/bin
    wget -O $HOME/bin/dropbox  "https://www.dropbox.com/download?dl=packages/dropbox.py"
    chmod +x $HOME/bin/dropbox
    dropbox start -i
    dropbox status
    read -n 1 -s -r -p "Visit the link above (if any) and press any key to continue"
    cd $HOME/Dropbox
    dropbox exclude add * > /dev/null
    dropbox exclude remove "$DROPBOX_DIR"
    echo "Setting Dropbox to autostart"
    dropbox autostart y
    echo "Waiting for Dropbox to sync..."
    sleep 3
    until dropbox filestatus "$DROPBOX_DIR" | grep up to date; do
        echo "Still waiting for Dropbox to sync..."
        sleep 5
    done

    if [ ! -d "$DROPBOX_DIR"]; then
        echo "Dropbox claims it's up to date, but $DROPBOX_DIR does not exist. Exiting."
        exit 1
    fi
    LINK_DIR="${HOME}/Dropbox/${DROPBOX_DIR}"
}